services:
  - type: web
    name: mi-api-sqlserver
    runtime: python
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SERVER
        value: 123.123.123.123          # ← tu IP pública o nombre DNS del SQL Server
      - key: DB
        value: SistradeERP
      - key: USER
        value: tu_usuario
      - key: PASSWORD
        value: tu_contraseña_segura
